// <auto-generated>
// Copyright © 2018 FINBOURNE TECHNOLOGY LTD
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.
// </auto-generated>

namespace Finbourne.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Summary information of a holdings adjustment for a single portfolio and
    /// effective date.
    /// </summary>
    public partial class HoldingsAdjustmentHeaderDto
    {
        /// <summary>
        /// Initializes a new instance of the HoldingsAdjustmentHeaderDto
        /// class.
        /// </summary>
        public HoldingsAdjustmentHeaderDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HoldingsAdjustmentHeaderDto
        /// class.
        /// </summary>
        /// <param name="effectiveAt">There can be at most one holdings
        /// adjustment for a portfolio at a
        /// specific effective time so this uniquely identifies the
        /// adjustment.</param>
        /// <param name="unmatchedHoldingMethod">Possible values include:
        /// 'PositionToZero', 'KeepTheSame'</param>
        public HoldingsAdjustmentHeaderDto(System.DateTimeOffset? effectiveAt = default(System.DateTimeOffset?), VersionDto version = default(VersionDto), string unmatchedHoldingMethod = default(string), IList<Link> links = default(IList<Link>))
        {
            EffectiveAt = effectiveAt;
            Version = version;
            UnmatchedHoldingMethod = unmatchedHoldingMethod;
            Links = links;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets there can be at most one holdings adjustment for a
        /// portfolio at a
        /// specific effective time so this uniquely identifies the adjustment.
        /// </summary>
        [JsonProperty(PropertyName = "effectiveAt")]
        public System.DateTimeOffset? EffectiveAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public VersionDto Version { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'PositionToZero',
        /// 'KeepTheSame'
        /// </summary>
        [JsonProperty(PropertyName = "unmatchedHoldingMethod")]
        public string UnmatchedHoldingMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "links")]
        public IList<Link> Links { get; set; }

    }
}
