/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Lusid.Sdk.Client.OpenAPIDateConverter;

namespace Lusid.Sdk.Model
{
    /// <summary>
    /// LUSID representation of an OTC bilateral commodity calendar swap.  The swap is a strip of periodic commodity forwards struck at a single strike, cash-settled at each  period end against a calendar-average commodity price, with the position amortising as each period  settles. Its present value is Quantity x Price, where the price is supplied externally pre-netted  (the calendar average minus strike) via the quote store. LUSID calculates no analytics for this  instrument, and it can only be priced by lookup pricing. The periodic settlement schedule is  currently stored and validated only; only the maturity lifecycle event is generated.
    /// </summary>
    [DataContract(Name = "CommodityCalendarSwap")]
    [JsonConverter(typeof(JsonSubtypes), "InstrumentType")]
    public partial class CommodityCalendarSwap : LusidInstrument, IEquatable<CommodityCalendarSwap>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CommodityCalendarSwap" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CommodityCalendarSwap() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CommodityCalendarSwap" /> class.
        /// </summary>
        /// <param name="domCcy">The domestic currency of the instrument. (required).</param>
        /// <param name="strike">Agreed price per unit at trade inception. Reference only - not used in the market value  calculation, which consumes the pre-netted price from the quote store..</param>
        /// <param name="commodityCalendarSchedule">commodityCalendarSchedule (required).</param>
        /// <param name="deliveryType">Whether the swap settles in cash or through physical delivery of the underlying.  Only cash settlement is supported.                Supported string (enumeration) values are: [Cash, Physical]. Available values: Cash, Physical. (required).</param>
        /// <param name="quantityPerPeriod">The notional commodity quantity referenced by each settlement period. The initial holding is  this quantity multiplied by the number of periods, stepping down by this quantity as each  period settles. (required).</param>
        /// <param name="underlying">underlying.</param>
        /// <param name="instrumentType">Available values: QuotedSecurity, InterestRateSwap, FxForward, Future, ExoticInstrument, FxOption, CreditDefaultSwap, InterestRateSwaption, Bond, EquityOption, FixedLeg, FloatingLeg, BespokeCashFlowsLeg, Unknown, TermDeposit, ContractForDifference, EquitySwap, CashPerpetual, CapFloor, CashSettled, CdsIndex, Basket, FundingLeg, FxSwap, ForwardRateAgreement, SimpleInstrument, Repo, Equity, ExchangeTradedOption, ReferenceInstrument, ComplexBond, InflationLinkedBond, InflationSwap, SimpleCashFlowLoan, TotalReturnSwap, InflationLeg, FundShareClass, FlexibleLoan, UnsettledCash, Cash, MasteredInstrument, LoanFacility, FlexibleDeposit, FlexibleRepo, ToBeAnnounced, VolatilitySwap, ToBeAnnouncedOption, CommodityForward, BondOption, CdsOption, CommodityCalendarSwap. (required) (default to &quot;CommodityCalendarSwap&quot;).</param>
        public CommodityCalendarSwap(string domCcy = default(string), decimal? strike = default(decimal?), CommodityCalendarSchedule commodityCalendarSchedule = default(CommodityCalendarSchedule), string deliveryType = default(string), decimal quantityPerPeriod = default(decimal), LusidInstrument underlying = default(LusidInstrument), InstrumentTypeEnum instrumentType = default(InstrumentTypeEnum)) : base(instrumentType)
        {
            // to ensure "domCcy" is required (not null)
            if (domCcy == null)
            {
                throw new ArgumentNullException("domCcy is a required property for CommodityCalendarSwap and cannot be null");
            }
            this.DomCcy = domCcy;
            // to ensure "commodityCalendarSchedule" is required (not null)
            if (commodityCalendarSchedule == null)
            {
                throw new ArgumentNullException("commodityCalendarSchedule is a required property for CommodityCalendarSwap and cannot be null");
            }
            this.CommodityCalendarSchedule = commodityCalendarSchedule;
            // to ensure "deliveryType" is required (not null)
            if (deliveryType == null)
            {
                throw new ArgumentNullException("deliveryType is a required property for CommodityCalendarSwap and cannot be null");
            }
            this.DeliveryType = deliveryType;
            this.QuantityPerPeriod = quantityPerPeriod;
            this.Strike = strike;
            this.Underlying = underlying;
        }

        /// <summary>
        /// The domestic currency of the instrument.
        /// </summary>
        /// <value>The domestic currency of the instrument.</value>
        [DataMember(Name = "domCcy", IsRequired = true, EmitDefaultValue = true)]
        public string DomCcy { get; set; }

        /// <summary>
        /// Agreed price per unit at trade inception. Reference only - not used in the market value  calculation, which consumes the pre-netted price from the quote store.
        /// </summary>
        /// <value>Agreed price per unit at trade inception. Reference only - not used in the market value  calculation, which consumes the pre-netted price from the quote store.</value>
        [DataMember(Name = "strike", EmitDefaultValue = true)]
        public decimal? Strike { get; set; }

        /// <summary>
        /// Gets or Sets CommodityCalendarSchedule
        /// </summary>
        [DataMember(Name = "commodityCalendarSchedule", IsRequired = true, EmitDefaultValue = true)]
        public CommodityCalendarSchedule CommodityCalendarSchedule { get; set; }

        /// <summary>
        /// Whether the swap settles in cash or through physical delivery of the underlying.  Only cash settlement is supported.                Supported string (enumeration) values are: [Cash, Physical]. Available values: Cash, Physical.
        /// </summary>
        /// <value>Whether the swap settles in cash or through physical delivery of the underlying.  Only cash settlement is supported.                Supported string (enumeration) values are: [Cash, Physical]. Available values: Cash, Physical.</value>
        [DataMember(Name = "deliveryType", IsRequired = true, EmitDefaultValue = true)]
        public string DeliveryType { get; set; }

        /// <summary>
        /// The notional commodity quantity referenced by each settlement period. The initial holding is  this quantity multiplied by the number of periods, stepping down by this quantity as each  period settles.
        /// </summary>
        /// <value>The notional commodity quantity referenced by each settlement period. The initial holding is  this quantity multiplied by the number of periods, stepping down by this quantity as each  period settles.</value>
        [DataMember(Name = "quantityPerPeriod", IsRequired = true, EmitDefaultValue = true)]
        public decimal QuantityPerPeriod { get; set; }

        /// <summary>
        /// Gets or Sets Underlying
        /// </summary>
        [DataMember(Name = "underlying", EmitDefaultValue = false)]
        public LusidInstrument Underlying { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CommodityCalendarSwap {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  DomCcy: ").Append(DomCcy).Append("\n");
            sb.Append("  Strike: ").Append(Strike).Append("\n");
            sb.Append("  CommodityCalendarSchedule: ").Append(CommodityCalendarSchedule).Append("\n");
            sb.Append("  DeliveryType: ").Append(DeliveryType).Append("\n");
            sb.Append("  QuantityPerPeriod: ").Append(QuantityPerPeriod).Append("\n");
            sb.Append("  Underlying: ").Append(Underlying).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CommodityCalendarSwap);
        }

        /// <summary>
        /// Returns true if CommodityCalendarSwap instances are equal
        /// </summary>
        /// <param name="input">Instance of CommodityCalendarSwap to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CommodityCalendarSwap input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.DomCcy == input.DomCcy ||
                    (this.DomCcy != null &&
                    this.DomCcy.Equals(input.DomCcy))
                ) && base.Equals(input) && 
                (
                    this.Strike == input.Strike ||
                    (this.Strike != null &&
                    this.Strike.Equals(input.Strike))
                ) && base.Equals(input) && 
                (
                    this.CommodityCalendarSchedule == input.CommodityCalendarSchedule ||
                    (this.CommodityCalendarSchedule != null &&
                    this.CommodityCalendarSchedule.Equals(input.CommodityCalendarSchedule))
                ) && base.Equals(input) && 
                (
                    this.DeliveryType == input.DeliveryType ||
                    (this.DeliveryType != null &&
                    this.DeliveryType.Equals(input.DeliveryType))
                ) && base.Equals(input) && 
                (
                    this.QuantityPerPeriod == input.QuantityPerPeriod ||
                    this.QuantityPerPeriod.Equals(input.QuantityPerPeriod)
                ) && base.Equals(input) && 
                (
                    this.Underlying == input.Underlying ||
                    (this.Underlying != null &&
                    this.Underlying.Equals(input.Underlying))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.DomCcy != null)
                {
                    hashCode = (hashCode * 59) + this.DomCcy.GetHashCode();
                }
                if (this.Strike != null)
                {
                    hashCode = (hashCode * 59) + this.Strike.GetHashCode();
                }
                if (this.CommodityCalendarSchedule != null)
                {
                    hashCode = (hashCode * 59) + this.CommodityCalendarSchedule.GetHashCode();
                }
                if (this.DeliveryType != null)
                {
                    hashCode = (hashCode * 59) + this.DeliveryType.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.QuantityPerPeriod.GetHashCode();
                if (this.Underlying != null)
                {
                    hashCode = (hashCode * 59) + this.Underlying.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            // DeliveryType (string) minLength
            if (this.DeliveryType != null && this.DeliveryType.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DeliveryType, length must be greater than 1.", new [] { "DeliveryType" });
            }

            yield break;
        }
    }
}
