/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Lusid.Sdk.Client.OpenAPIDateConverter;

namespace Lusid.Sdk.Model
{
    /// <summary>
    /// Which bounds of a curve shift&#39;s tenor window admit a pillar sitting exactly on them.  Inclusive - the closed window [StartTenor, EndTenor], and the behaviour of every scenario  stored before this field existed - is the default. An exclusive bound rejects the pillar  sitting exactly on it, which is what lets two adjacent windows share a boundary tenor  without both shifting that pillar: a shift over [A, B) composed with one over [B, C]  moves the pillar at B exactly once, where two inclusive windows would both match it and  their amounts would add.
    /// </summary>
    /// <value>Which bounds of a curve shift&#39;s tenor window admit a pillar sitting exactly on them.  Inclusive - the closed window [StartTenor, EndTenor], and the behaviour of every scenario  stored before this field existed - is the default. An exclusive bound rejects the pillar  sitting exactly on it, which is what lets two adjacent windows share a boundary tenor  without both shifting that pillar: a shift over [A, B) composed with one over [B, C]  moves the pillar at B exactly once, where two inclusive windows would both match it and  their amounts would add.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CurveShiftWindowBounds
    {
        /// <summary>
        /// Enum Inclusive for value: Inclusive
        /// </summary>
        [EnumMember(Value = "Inclusive")]
        Inclusive = 1,

        /// <summary>
        /// Enum StartExclusive for value: StartExclusive
        /// </summary>
        [EnumMember(Value = "StartExclusive")]
        StartExclusive = 2,

        /// <summary>
        /// Enum EndExclusive for value: EndExclusive
        /// </summary>
        [EnumMember(Value = "EndExclusive")]
        EndExclusive = 3,

        /// <summary>
        /// Enum Exclusive for value: Exclusive
        /// </summary>
        [EnumMember(Value = "Exclusive")]
        Exclusive = 4
    }

}
