/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Lusid.Sdk.Client.OpenAPIDateConverter;

namespace Lusid.Sdk.Model
{
    /// <summary>
    /// CustodianEntry
    /// </summary>
    [DataContract(Name = "CustodianEntry")]
    public partial class CustodianEntry : IEquatable<CustodianEntry>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustodianEntry" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CustodianEntry() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CustodianEntry" /> class.
        /// </summary>
        /// <param name="accountId">accountId (required).</param>
        /// <param name="accountSelector">Available values: From, To..</param>
        public CustodianEntry(ResourceId accountId = default(ResourceId), string accountSelector = default(string))
        {
            // to ensure "accountId" is required (not null)
            if (accountId == null)
            {
                throw new ArgumentNullException("accountId is a required property for CustodianEntry and cannot be null");
            }
            this.AccountId = accountId;
            this.AccountSelector = accountSelector;
        }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "accountId", IsRequired = true, EmitDefaultValue = true)]
        public ResourceId AccountId { get; set; }

        /// <summary>
        /// Available values: From, To.
        /// </summary>
        /// <value>Available values: From, To.</value>
        [DataMember(Name = "accountSelector", EmitDefaultValue = true)]
        public string AccountSelector { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustodianEntry {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  AccountSelector: ").Append(AccountSelector).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CustodianEntry);
        }

        /// <summary>
        /// Returns true if CustodianEntry instances are equal
        /// </summary>
        /// <param name="input">Instance of CustodianEntry to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CustodianEntry input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AccountId == input.AccountId ||
                    (this.AccountId != null &&
                    this.AccountId.Equals(input.AccountId))
                ) && 
                (
                    this.AccountSelector == input.AccountSelector ||
                    (this.AccountSelector != null &&
                    this.AccountSelector.Equals(input.AccountSelector))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AccountId != null)
                {
                    hashCode = (hashCode * 59) + this.AccountId.GetHashCode();
                }
                if (this.AccountSelector != null)
                {
                    hashCode = (hashCode * 59) + this.AccountSelector.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
