/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Lusid.Sdk.Client.OpenAPIDateConverter;

namespace Lusid.Sdk.Model
{
    /// <summary>
    /// GroupReconciliationUserReviewComment
    /// </summary>
    [DataContract(Name = "GroupReconciliationUserReviewComment")]
    public partial class GroupReconciliationUserReviewComment : IEquatable<GroupReconciliationUserReviewComment>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GroupReconciliationUserReviewComment" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GroupReconciliationUserReviewComment() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GroupReconciliationUserReviewComment" /> class.
        /// </summary>
        /// <param name="commentText">User&#39;s comment regarding the reconciliation result. (required).</param>
        /// <param name="userId">Id of the user who made a User Review input..</param>
        /// <param name="asAtAdded">The timestamp of the added User Review input..</param>
        /// <param name="asAtInvalid">The timestamp when User Review input became invalid e.g. because of the different attribute values within the new run..</param>
        public GroupReconciliationUserReviewComment(string commentText = default(string), string userId = default(string), DateTimeOffset asAtAdded = default(DateTimeOffset), DateTimeOffset asAtInvalid = default(DateTimeOffset))
        {
            // to ensure "commentText" is required (not null)
            if (commentText == null)
            {
                throw new ArgumentNullException("commentText is a required property for GroupReconciliationUserReviewComment and cannot be null");
            }
            this.CommentText = commentText;
            this.UserId = userId;
            this.AsAtAdded = asAtAdded;
            this.AsAtInvalid = asAtInvalid;
        }

        /// <summary>
        /// User&#39;s comment regarding the reconciliation result.
        /// </summary>
        /// <value>User&#39;s comment regarding the reconciliation result.</value>
        [DataMember(Name = "commentText", IsRequired = true, EmitDefaultValue = true)]
        public string CommentText { get; set; }

        /// <summary>
        /// Id of the user who made a User Review input.
        /// </summary>
        /// <value>Id of the user who made a User Review input.</value>
        [DataMember(Name = "userId", EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        /// The timestamp of the added User Review input.
        /// </summary>
        /// <value>The timestamp of the added User Review input.</value>
        [DataMember(Name = "asAtAdded", EmitDefaultValue = false)]
        public DateTimeOffset AsAtAdded { get; set; }

        /// <summary>
        /// The timestamp when User Review input became invalid e.g. because of the different attribute values within the new run.
        /// </summary>
        /// <value>The timestamp when User Review input became invalid e.g. because of the different attribute values within the new run.</value>
        [DataMember(Name = "asAtInvalid", EmitDefaultValue = false)]
        public DateTimeOffset AsAtInvalid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GroupReconciliationUserReviewComment {\n");
            sb.Append("  CommentText: ").Append(CommentText).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  AsAtAdded: ").Append(AsAtAdded).Append("\n");
            sb.Append("  AsAtInvalid: ").Append(AsAtInvalid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GroupReconciliationUserReviewComment);
        }

        /// <summary>
        /// Returns true if GroupReconciliationUserReviewComment instances are equal
        /// </summary>
        /// <param name="input">Instance of GroupReconciliationUserReviewComment to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GroupReconciliationUserReviewComment input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CommentText == input.CommentText ||
                    (this.CommentText != null &&
                    this.CommentText.Equals(input.CommentText))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.AsAtAdded == input.AsAtAdded ||
                    (this.AsAtAdded != null &&
                    this.AsAtAdded.Equals(input.AsAtAdded))
                ) && 
                (
                    this.AsAtInvalid == input.AsAtInvalid ||
                    (this.AsAtInvalid != null &&
                    this.AsAtInvalid.Equals(input.AsAtInvalid))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CommentText != null)
                {
                    hashCode = (hashCode * 59) + this.CommentText.GetHashCode();
                }
                if (this.UserId != null)
                {
                    hashCode = (hashCode * 59) + this.UserId.GetHashCode();
                }
                if (this.AsAtAdded != null)
                {
                    hashCode = (hashCode * 59) + this.AsAtAdded.GetHashCode();
                }
                if (this.AsAtInvalid != null)
                {
                    hashCode = (hashCode * 59) + this.AsAtInvalid.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CommentText (string) minLength
            if (this.CommentText != null && this.CommentText.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CommentText, length must be greater than 1.", new [] { "CommentText" });
            }

            // UserId (string) maxLength
            if (this.UserId != null && this.UserId.Length > 16384)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for UserId, length must be less than 16384.", new [] { "UserId" });
            }

            // UserId (string) minLength
            if (this.UserId != null && this.UserId.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for UserId, length must be greater than 0.", new [] { "UserId" });
            }

            yield break;
        }
    }
}
