/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Lusid.Sdk.Client.OpenAPIDateConverter;

namespace Lusid.Sdk.Model
{
    /// <summary>
    /// InstrumentResolutionDetail
    /// </summary>
    [DataContract(Name = "InstrumentResolutionDetail")]
    public partial class InstrumentResolutionDetail : IEquatable<InstrumentResolutionDetail>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstrumentResolutionDetail" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InstrumentResolutionDetail() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InstrumentResolutionDetail" /> class.
        /// </summary>
        /// <param name="instrumentIdentifiers">Unique instrument identifiers (required).</param>
        /// <param name="launchPrice">The launch price set when a shareclass is added to the fund. Defaults to 1..</param>
        /// <param name="launchDate">The launch date set when a shareclass is added to the fund. Defaults to Fund Inception Date..</param>
        public InstrumentResolutionDetail(Dictionary<string, string> instrumentIdentifiers = default(Dictionary<string, string>), decimal? launchPrice = default(decimal?), DateTimeOffset? launchDate = default(DateTimeOffset?))
        {
            // to ensure "instrumentIdentifiers" is required (not null)
            if (instrumentIdentifiers == null)
            {
                throw new ArgumentNullException("instrumentIdentifiers is a required property for InstrumentResolutionDetail and cannot be null");
            }
            this.InstrumentIdentifiers = instrumentIdentifiers;
            this.LaunchPrice = launchPrice;
            this.LaunchDate = launchDate;
        }

        /// <summary>
        /// Unique instrument identifiers
        /// </summary>
        /// <value>Unique instrument identifiers</value>
        [DataMember(Name = "instrumentIdentifiers", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, string> InstrumentIdentifiers { get; set; }

        /// <summary>
        /// LUSID&#39;s internal unique instrument identifier, resolved from the instrument identifiers
        /// </summary>
        /// <value>LUSID&#39;s internal unique instrument identifier, resolved from the instrument identifiers</value>
        [DataMember(Name = "lusidInstrumentId", EmitDefaultValue = true)]
        public string LusidInstrumentId { get; private set; }

        /// <summary>
        /// Returns false as LusidInstrumentId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeLusidInstrumentId()
        {
            return false;
        }
        /// <summary>
        /// The scope in which the instrument lies.
        /// </summary>
        /// <value>The scope in which the instrument lies.</value>
        [DataMember(Name = "instrumentScope", EmitDefaultValue = true)]
        public string InstrumentScope { get; private set; }

        /// <summary>
        /// Returns false as InstrumentScope should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeInstrumentScope()
        {
            return false;
        }
        /// <summary>
        /// The launch price set when a shareclass is added to the fund. Defaults to 1.
        /// </summary>
        /// <value>The launch price set when a shareclass is added to the fund. Defaults to 1.</value>
        [DataMember(Name = "launchPrice", EmitDefaultValue = true)]
        public decimal? LaunchPrice { get; set; }

        /// <summary>
        /// The launch date set when a shareclass is added to the fund. Defaults to Fund Inception Date.
        /// </summary>
        /// <value>The launch date set when a shareclass is added to the fund. Defaults to Fund Inception Date.</value>
        [DataMember(Name = "launchDate", EmitDefaultValue = true)]
        public DateTimeOffset? LaunchDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstrumentResolutionDetail {\n");
            sb.Append("  InstrumentIdentifiers: ").Append(InstrumentIdentifiers).Append("\n");
            sb.Append("  LusidInstrumentId: ").Append(LusidInstrumentId).Append("\n");
            sb.Append("  InstrumentScope: ").Append(InstrumentScope).Append("\n");
            sb.Append("  LaunchPrice: ").Append(LaunchPrice).Append("\n");
            sb.Append("  LaunchDate: ").Append(LaunchDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InstrumentResolutionDetail);
        }

        /// <summary>
        /// Returns true if InstrumentResolutionDetail instances are equal
        /// </summary>
        /// <param name="input">Instance of InstrumentResolutionDetail to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InstrumentResolutionDetail input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.InstrumentIdentifiers == input.InstrumentIdentifiers ||
                    this.InstrumentIdentifiers != null &&
                    input.InstrumentIdentifiers != null &&
                    this.InstrumentIdentifiers.SequenceEqual(input.InstrumentIdentifiers)
                ) && 
                (
                    this.LusidInstrumentId == input.LusidInstrumentId ||
                    (this.LusidInstrumentId != null &&
                    this.LusidInstrumentId.Equals(input.LusidInstrumentId))
                ) && 
                (
                    this.InstrumentScope == input.InstrumentScope ||
                    (this.InstrumentScope != null &&
                    this.InstrumentScope.Equals(input.InstrumentScope))
                ) && 
                (
                    this.LaunchPrice == input.LaunchPrice ||
                    (this.LaunchPrice != null &&
                    this.LaunchPrice.Equals(input.LaunchPrice))
                ) && 
                (
                    this.LaunchDate == input.LaunchDate ||
                    (this.LaunchDate != null &&
                    this.LaunchDate.Equals(input.LaunchDate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InstrumentIdentifiers != null)
                {
                    hashCode = (hashCode * 59) + this.InstrumentIdentifiers.GetHashCode();
                }
                if (this.LusidInstrumentId != null)
                {
                    hashCode = (hashCode * 59) + this.LusidInstrumentId.GetHashCode();
                }
                if (this.InstrumentScope != null)
                {
                    hashCode = (hashCode * 59) + this.InstrumentScope.GetHashCode();
                }
                if (this.LaunchPrice != null)
                {
                    hashCode = (hashCode * 59) + this.LaunchPrice.GetHashCode();
                }
                if (this.LaunchDate != null)
                {
                    hashCode = (hashCode * 59) + this.LaunchDate.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // LusidInstrumentId (string) maxLength
            if (this.LusidInstrumentId != null && this.LusidInstrumentId.Length > 64)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LusidInstrumentId, length must be less than 64.", new [] { "LusidInstrumentId" });
            }

            // LusidInstrumentId (string) minLength
            if (this.LusidInstrumentId != null && this.LusidInstrumentId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LusidInstrumentId, length must be greater than 1.", new [] { "LusidInstrumentId" });
            }

            // LusidInstrumentId (string) pattern
            Regex regexLusidInstrumentId = new Regex(@"^[a-zA-Z0-9\-_]+$", RegexOptions.CultureInvariant);
            if (false == regexLusidInstrumentId.Match(this.LusidInstrumentId).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LusidInstrumentId, must match a pattern of " + regexLusidInstrumentId, new [] { "LusidInstrumentId" });
            }

            // InstrumentScope (string) maxLength
            if (this.InstrumentScope != null && this.InstrumentScope.Length > 64)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for InstrumentScope, length must be less than 64.", new [] { "InstrumentScope" });
            }

            // InstrumentScope (string) minLength
            if (this.InstrumentScope != null && this.InstrumentScope.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for InstrumentScope, length must be greater than 1.", new [] { "InstrumentScope" });
            }

            // InstrumentScope (string) pattern
            Regex regexInstrumentScope = new Regex(@"^[a-zA-Z0-9\-_]+$", RegexOptions.CultureInvariant);
            if (false == regexInstrumentScope.Match(this.InstrumentScope).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for InstrumentScope, must match a pattern of " + regexInstrumentScope, new [] { "InstrumentScope" });
            }

            yield break;
        }
    }
}
