/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Lusid.Sdk.Client.OpenAPIDateConverter;

namespace Lusid.Sdk.Model
{
    /// <summary>
    /// A request to create or update a Payment Instruction. Status is not accepted here —  status transitions are managed exclusively via the dedicated Payment Instruction status API.
    /// </summary>
    [DataContract(Name = "PaymentInstructionRequest")]
    public partial class PaymentInstructionRequest : IEquatable<PaymentInstructionRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentInstructionRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PaymentInstructionRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentInstructionRequest" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="paymentRecordIds">One or more Payment Records batched into this instruction block. All referenced Payment Records must share the same currency as the top-level currency field. (required).</param>
        /// <param name="currency">ISO 4217 currency code. All referenced Payment Records must share this currency value. (required).</param>
        /// <param name="totalPaymentAmount">Total payment amount across all referenced Payment Records. (required).</param>
        /// <param name="paymentDate">The value date on which settlement is due. ISO 8601 date. (required).</param>
        /// <param name="payorPaymentDetailsReference">payorPaymentDetailsReference (required).</param>
        /// <param name="payeePaymentDetailsReference">payeePaymentDetailsReference (required).</param>
        /// <param name="properties">Client-defined properties associated with this Payment Instruction..</param>
        public PaymentInstructionRequest(ResourceId id = default(ResourceId), List<PaymentRecordReference> paymentRecordIds = default(List<PaymentRecordReference>), string currency = default(string), decimal totalPaymentAmount = default(decimal), DateTimeOffset paymentDate = default(DateTimeOffset), PaymentDetailsReference payorPaymentDetailsReference = default(PaymentDetailsReference), PaymentDetailsReference payeePaymentDetailsReference = default(PaymentDetailsReference), Dictionary<string, PerpetualProperty> properties = default(Dictionary<string, PerpetualProperty>))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for PaymentInstructionRequest and cannot be null");
            }
            this.Id = id;
            // to ensure "paymentRecordIds" is required (not null)
            if (paymentRecordIds == null)
            {
                throw new ArgumentNullException("paymentRecordIds is a required property for PaymentInstructionRequest and cannot be null");
            }
            this.PaymentRecordIds = paymentRecordIds;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for PaymentInstructionRequest and cannot be null");
            }
            this.Currency = currency;
            this.TotalPaymentAmount = totalPaymentAmount;
            this.PaymentDate = paymentDate;
            // to ensure "payorPaymentDetailsReference" is required (not null)
            if (payorPaymentDetailsReference == null)
            {
                throw new ArgumentNullException("payorPaymentDetailsReference is a required property for PaymentInstructionRequest and cannot be null");
            }
            this.PayorPaymentDetailsReference = payorPaymentDetailsReference;
            // to ensure "payeePaymentDetailsReference" is required (not null)
            if (payeePaymentDetailsReference == null)
            {
                throw new ArgumentNullException("payeePaymentDetailsReference is a required property for PaymentInstructionRequest and cannot be null");
            }
            this.PayeePaymentDetailsReference = payeePaymentDetailsReference;
            this.Properties = properties;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public ResourceId Id { get; set; }

        /// <summary>
        /// One or more Payment Records batched into this instruction block. All referenced Payment Records must share the same currency as the top-level currency field.
        /// </summary>
        /// <value>One or more Payment Records batched into this instruction block. All referenced Payment Records must share the same currency as the top-level currency field.</value>
        [DataMember(Name = "paymentRecordIds", IsRequired = true, EmitDefaultValue = true)]
        public List<PaymentRecordReference> PaymentRecordIds { get; set; }

        /// <summary>
        /// ISO 4217 currency code. All referenced Payment Records must share this currency value.
        /// </summary>
        /// <value>ISO 4217 currency code. All referenced Payment Records must share this currency value.</value>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Total payment amount across all referenced Payment Records.
        /// </summary>
        /// <value>Total payment amount across all referenced Payment Records.</value>
        [DataMember(Name = "totalPaymentAmount", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalPaymentAmount { get; set; }

        /// <summary>
        /// The value date on which settlement is due. ISO 8601 date.
        /// </summary>
        /// <value>The value date on which settlement is due. ISO 8601 date.</value>
        [DataMember(Name = "paymentDate", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset PaymentDate { get; set; }

        /// <summary>
        /// Gets or Sets PayorPaymentDetailsReference
        /// </summary>
        [DataMember(Name = "payorPaymentDetailsReference", IsRequired = true, EmitDefaultValue = true)]
        public PaymentDetailsReference PayorPaymentDetailsReference { get; set; }

        /// <summary>
        /// Gets or Sets PayeePaymentDetailsReference
        /// </summary>
        [DataMember(Name = "payeePaymentDetailsReference", IsRequired = true, EmitDefaultValue = true)]
        public PaymentDetailsReference PayeePaymentDetailsReference { get; set; }

        /// <summary>
        /// Client-defined properties associated with this Payment Instruction.
        /// </summary>
        /// <value>Client-defined properties associated with this Payment Instruction.</value>
        [DataMember(Name = "properties", EmitDefaultValue = true)]
        public Dictionary<string, PerpetualProperty> Properties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentInstructionRequest {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PaymentRecordIds: ").Append(PaymentRecordIds).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  TotalPaymentAmount: ").Append(TotalPaymentAmount).Append("\n");
            sb.Append("  PaymentDate: ").Append(PaymentDate).Append("\n");
            sb.Append("  PayorPaymentDetailsReference: ").Append(PayorPaymentDetailsReference).Append("\n");
            sb.Append("  PayeePaymentDetailsReference: ").Append(PayeePaymentDetailsReference).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentInstructionRequest);
        }

        /// <summary>
        /// Returns true if PaymentInstructionRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentInstructionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentInstructionRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.PaymentRecordIds == input.PaymentRecordIds ||
                    this.PaymentRecordIds != null &&
                    input.PaymentRecordIds != null &&
                    this.PaymentRecordIds.SequenceEqual(input.PaymentRecordIds)
                ) && 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                ) && 
                (
                    this.TotalPaymentAmount == input.TotalPaymentAmount ||
                    this.TotalPaymentAmount.Equals(input.TotalPaymentAmount)
                ) && 
                (
                    this.PaymentDate == input.PaymentDate ||
                    (this.PaymentDate != null &&
                    this.PaymentDate.Equals(input.PaymentDate))
                ) && 
                (
                    this.PayorPaymentDetailsReference == input.PayorPaymentDetailsReference ||
                    (this.PayorPaymentDetailsReference != null &&
                    this.PayorPaymentDetailsReference.Equals(input.PayorPaymentDetailsReference))
                ) && 
                (
                    this.PayeePaymentDetailsReference == input.PayeePaymentDetailsReference ||
                    (this.PayeePaymentDetailsReference != null &&
                    this.PayeePaymentDetailsReference.Equals(input.PayeePaymentDetailsReference))
                ) && 
                (
                    this.Properties == input.Properties ||
                    this.Properties != null &&
                    input.Properties != null &&
                    this.Properties.SequenceEqual(input.Properties)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.PaymentRecordIds != null)
                {
                    hashCode = (hashCode * 59) + this.PaymentRecordIds.GetHashCode();
                }
                if (this.Currency != null)
                {
                    hashCode = (hashCode * 59) + this.Currency.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.TotalPaymentAmount.GetHashCode();
                if (this.PaymentDate != null)
                {
                    hashCode = (hashCode * 59) + this.PaymentDate.GetHashCode();
                }
                if (this.PayorPaymentDetailsReference != null)
                {
                    hashCode = (hashCode * 59) + this.PayorPaymentDetailsReference.GetHashCode();
                }
                if (this.PayeePaymentDetailsReference != null)
                {
                    hashCode = (hashCode * 59) + this.PayeePaymentDetailsReference.GetHashCode();
                }
                if (this.Properties != null)
                {
                    hashCode = (hashCode * 59) + this.Properties.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
