/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Lusid.Sdk.Client.OpenAPIDateConverter;

namespace Lusid.Sdk.Model
{
    /// <summary>
    /// The units of a rate curve shift&#39;s amount: basis points for absolute shifts, percentage for  relative shifts.
    /// </summary>
    /// <value>The units of a rate curve shift&#39;s amount: basis points for absolute shifts, percentage for  relative shifts.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RateCurveShiftScale
    {
        /// <summary>
        /// Enum Bps for value: Bps
        /// </summary>
        [EnumMember(Value = "Bps")]
        Bps = 1,

        /// <summary>
        /// Enum Percentage for value: Percentage
        /// </summary>
        [EnumMember(Value = "Percentage")]
        Percentage = 2
    }

}
