/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Lusid.Sdk.Client.OpenAPIDateConverter;

namespace Lusid.Sdk.Model
{
    /// <summary>
    /// A user-authored comment attached to a rec result. Carried forward with the result across runs.
    /// </summary>
    [DataContract(Name = "RecUserComment")]
    public partial class RecUserComment : IEquatable<RecUserComment>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecUserComment" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RecUserComment() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RecUserComment" /> class.
        /// </summary>
        /// <param name="commentId">System-generated GUID identifying the comment. Set once on creation. (required).</param>
        /// <param name="commentText">The body of the comment. (required).</param>
        /// <param name="userId">The author of the comment. (required).</param>
        /// <param name="asAtCreated">The asAt time the comment was created. Set once. (required).</param>
        /// <param name="asAtModified">The asAt time the comment was last modified. Equals asAtCreated until the first edit. (required).</param>
        public RecUserComment(string commentId = default(string), string commentText = default(string), string userId = default(string), DateTimeOffset asAtCreated = default(DateTimeOffset), DateTimeOffset asAtModified = default(DateTimeOffset))
        {
            // to ensure "commentId" is required (not null)
            if (commentId == null)
            {
                throw new ArgumentNullException("commentId is a required property for RecUserComment and cannot be null");
            }
            this.CommentId = commentId;
            // to ensure "commentText" is required (not null)
            if (commentText == null)
            {
                throw new ArgumentNullException("commentText is a required property for RecUserComment and cannot be null");
            }
            this.CommentText = commentText;
            // to ensure "userId" is required (not null)
            if (userId == null)
            {
                throw new ArgumentNullException("userId is a required property for RecUserComment and cannot be null");
            }
            this.UserId = userId;
            this.AsAtCreated = asAtCreated;
            this.AsAtModified = asAtModified;
        }

        /// <summary>
        /// System-generated GUID identifying the comment. Set once on creation.
        /// </summary>
        /// <value>System-generated GUID identifying the comment. Set once on creation.</value>
        [DataMember(Name = "commentId", IsRequired = true, EmitDefaultValue = true)]
        public string CommentId { get; set; }

        /// <summary>
        /// The body of the comment.
        /// </summary>
        /// <value>The body of the comment.</value>
        [DataMember(Name = "commentText", IsRequired = true, EmitDefaultValue = true)]
        public string CommentText { get; set; }

        /// <summary>
        /// The author of the comment.
        /// </summary>
        /// <value>The author of the comment.</value>
        [DataMember(Name = "userId", IsRequired = true, EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        /// The asAt time the comment was created. Set once.
        /// </summary>
        /// <value>The asAt time the comment was created. Set once.</value>
        [DataMember(Name = "asAtCreated", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset AsAtCreated { get; set; }

        /// <summary>
        /// The asAt time the comment was last modified. Equals asAtCreated until the first edit.
        /// </summary>
        /// <value>The asAt time the comment was last modified. Equals asAtCreated until the first edit.</value>
        [DataMember(Name = "asAtModified", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset AsAtModified { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RecUserComment {\n");
            sb.Append("  CommentId: ").Append(CommentId).Append("\n");
            sb.Append("  CommentText: ").Append(CommentText).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  AsAtCreated: ").Append(AsAtCreated).Append("\n");
            sb.Append("  AsAtModified: ").Append(AsAtModified).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RecUserComment);
        }

        /// <summary>
        /// Returns true if RecUserComment instances are equal
        /// </summary>
        /// <param name="input">Instance of RecUserComment to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RecUserComment input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CommentId == input.CommentId ||
                    (this.CommentId != null &&
                    this.CommentId.Equals(input.CommentId))
                ) && 
                (
                    this.CommentText == input.CommentText ||
                    (this.CommentText != null &&
                    this.CommentText.Equals(input.CommentText))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.AsAtCreated == input.AsAtCreated ||
                    (this.AsAtCreated != null &&
                    this.AsAtCreated.Equals(input.AsAtCreated))
                ) && 
                (
                    this.AsAtModified == input.AsAtModified ||
                    (this.AsAtModified != null &&
                    this.AsAtModified.Equals(input.AsAtModified))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CommentId != null)
                {
                    hashCode = (hashCode * 59) + this.CommentId.GetHashCode();
                }
                if (this.CommentText != null)
                {
                    hashCode = (hashCode * 59) + this.CommentText.GetHashCode();
                }
                if (this.UserId != null)
                {
                    hashCode = (hashCode * 59) + this.UserId.GetHashCode();
                }
                if (this.AsAtCreated != null)
                {
                    hashCode = (hashCode * 59) + this.AsAtCreated.GetHashCode();
                }
                if (this.AsAtModified != null)
                {
                    hashCode = (hashCode * 59) + this.AsAtModified.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CommentId (string) minLength
            if (this.CommentId != null && this.CommentId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CommentId, length must be greater than 1.", new [] { "CommentId" });
            }

            // CommentText (string) minLength
            if (this.CommentText != null && this.CommentText.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CommentText, length must be greater than 1.", new [] { "CommentText" });
            }

            // UserId (string) minLength
            if (this.UserId != null && this.UserId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for UserId, length must be greater than 1.", new [] { "UserId" });
            }

            yield break;
        }
    }
}
