/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Lusid.Sdk.Client.OpenAPIDateConverter;

namespace Lusid.Sdk.Model
{
    /// <summary>
    /// UpsertDataQualityRule
    /// </summary>
    [DataContract(Name = "UpsertDataQualityRule")]
    public partial class UpsertDataQualityRule : IEquatable<UpsertDataQualityRule>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpsertDataQualityRule" /> class.
        /// </summary>
        /// <param name="ruleSetKey">ruleSetKey.</param>
        /// <param name="rule">rule.</param>
        public UpsertDataQualityRule(string ruleSetKey = default(string), CheckDefinitionRule rule = default(CheckDefinitionRule))
        {
            this.RuleSetKey = ruleSetKey;
            this.Rule = rule;
        }

        /// <summary>
        /// Gets or Sets RuleSetKey
        /// </summary>
        [DataMember(Name = "ruleSetKey", EmitDefaultValue = true)]
        public string RuleSetKey { get; set; }

        /// <summary>
        /// Gets or Sets Rule
        /// </summary>
        [DataMember(Name = "rule", EmitDefaultValue = false)]
        public CheckDefinitionRule Rule { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpsertDataQualityRule {\n");
            sb.Append("  RuleSetKey: ").Append(RuleSetKey).Append("\n");
            sb.Append("  Rule: ").Append(Rule).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpsertDataQualityRule);
        }

        /// <summary>
        /// Returns true if UpsertDataQualityRule instances are equal
        /// </summary>
        /// <param name="input">Instance of UpsertDataQualityRule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpsertDataQualityRule input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RuleSetKey == input.RuleSetKey ||
                    (this.RuleSetKey != null &&
                    this.RuleSetKey.Equals(input.RuleSetKey))
                ) && 
                (
                    this.Rule == input.Rule ||
                    (this.Rule != null &&
                    this.Rule.Equals(input.Rule))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RuleSetKey != null)
                {
                    hashCode = (hashCode * 59) + this.RuleSetKey.GetHashCode();
                }
                if (this.Rule != null)
                {
                    hashCode = (hashCode * 59) + this.Rule.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RuleSetKey (string) maxLength
            if (this.RuleSetKey != null && this.RuleSetKey.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RuleSetKey, length must be less than 50.", new [] { "RuleSetKey" });
            }

            // RuleSetKey (string) minLength
            if (this.RuleSetKey != null && this.RuleSetKey.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RuleSetKey, length must be greater than 0.", new [] { "RuleSetKey" });
            }

            yield break;
        }
    }
}
